# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0005_auto_20170905_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommender', models.CharField(max_length=30, null=True, verbose_name='推荐人')),
                ('recommendTime', models.DateTimeField(null=True, verbose_name='推荐时间')),
                ('recommendOpinion', models.TextField(null=True, verbose_name='推荐意见')),
                ('recommendStatus', models.CharField(choices=[('0', '强烈推荐'), ('1', '推荐'), ('2', '弱推荐'), ('3', '弱拒绝'), ('4', '拒绝'), ('5', '强烈拒绝')], max_length=1, null=True, verbose_name='推荐状态')),
            ],
            options={
                'verbose_name': '推荐',
                'verbose_name_plural': '推荐',
            },
        ),
        migrations.AlterField(
            model_name='journal',
            name='jourLevel',
            field=models.CharField(choices=[('A1', 'A1学术期刊'), ('A2', 'A2学术期刊'), ('B1', 'B1学术期刊'), ('B2', 'B2学术期刊'), ('C', 'C普通期刊')], max_length=4, null=True, verbose_name='期刊等级'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artical.journal'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artical.paper'),
        ),
    ]
