# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0006_auto_20170905_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='authorEmail',
            field=models.EmailField(max_length=128, null=True, verbose_name='作者邮件地址'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='jourEmail',
            field=models.EmailField(max_length=128, null=True, verbose_name='期刊邮件地址'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='reviewerEmail',
            field=models.EmailField(max_length=128, verbose_name='邮件地址'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='reviewerSecondEmail',
            field=models.EmailField(max_length=128, verbose_name='备用邮箱'),
        ),
    ]
