# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0007_auto_20170906_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_Theme',
            field=models.CharField(max_length=255, null=True, verbose_name='论文主题'),
        ),
    ]
