# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0008_paper_paper_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='paper_theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('important_Order', models.CharField(max_length=255, null=True, verbose_name='重要程度顺序')),
            ],
            options={
                'verbose_name': '论文-主题',
                'verbose_name_plural': '论文-主题',
            },
        ),
        migrations.CreateModel(
            name='theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_ChineseName', models.CharField(max_length=255, null=True, verbose_name='主题中文名称')),
                ('theme_EnglishName', models.CharField(max_length=255, null=True, verbose_name='主题英文名称')),
            ],
            options={
                'verbose_name': '论文主题',
                'verbose_name_plural': '论文主题',
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_ModifyTime',
            field=models.DateTimeField(null=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_Scores',
            field=models.FloatField(null=True, verbose_name='论文分数'),
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_level',
            field=models.CharField(choices=[('0', '非优秀论文'), ('1', '一等论文'), ('2', '二等论文'), ('3', '三等论文')], max_length=1, null=True, verbose_name='论文优秀等级'),
        ),
        migrations.AddField(
            model_name='paper',
            name='submission_Time',
            field=models.DateTimeField(null=True, verbose_name='投稿时间'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_Scores',
            field=models.FloatField(null=True, verbose_name='论文评分'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_paper_Kmownlevel',
            field=models.CharField(choices=[('10', '10分（最为熟悉）'), ('9', '9分'), ('8', '8分'), ('7', '7分'), ('6', '6分'), ('5', '5分'), ('4', '4分'), ('3', '3分'), ('2', '2分'), ('1', '1分（最不熟悉）')], max_length=2, null=True, verbose_name='专家对论文的熟悉程度'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='reviewer_IDnumber',
            field=models.CharField(max_length=18, null=True, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='reviewer_Sex',
            field=models.CharField(choices=[('0', '男'), ('1', '女')], max_length=1, null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='reviewer_birth',
            field=models.DateTimeField(null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='author',
            name='paper',
            field=models.ManyToManyField(blank=True, to='artical.paper'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paperEnglishSummary',
            field=models.CharField(max_length=1000, null=True, verbose_name='论文英文摘要'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paperFiles',
            field=models.FileField(null=True, upload_to='', verbose_name='论文附件'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='recommendStatus',
            field=models.CharField(choices=[('0', '已推荐'), ('1', '在审稿'), ('2', '在录用'), ('3', '被拒绝')], max_length=1, null=True, verbose_name='推荐状态'),
        ),
        migrations.AddField(
            model_name='theme',
            name='paper',
            field=models.ManyToManyField(to='artical.paper'),
        ),
        migrations.AddField(
            model_name='paper_theme',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artical.paper'),
        ),
        migrations.AddField(
            model_name='paper_theme',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artical.theme'),
        ),
    ]
