# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0009_auto_20170923_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_reported',
            field=models.BooleanField(default=False, verbose_name='论文是否已报告'),
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_reportNumber',
            field=models.IntegerField(null=True, verbose_name='论文报告序号'),
        ),
    ]
