# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentContent',
            field=models.TextField(null=True, verbose_name='评论内容'),
        ),
    ]
