# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_comment_commentcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_status',
            field=models.CharField(choices=[('0', '未缴费'), ('1', '等待中'), ('2', '缴费成功')], max_length=1, null=True, verbose_name='缴费状态'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pay_type',
            field=models.CharField(choices=[('0', '在线支付'), ('1', '现场刷卡')], max_length=1, null=True, verbose_name='支付类型'),
        ),
        migrations.AddField(
            model_name='user',
            name='register_type',
            field=models.CharField(choices=[('0', '学生'), ('1', '普通'), ('2', 'CCF')], max_length=1, null=True, verbose_name='注册类型'),
        ),
    ]
