# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20170920_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='conferenceTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conferenceTeam_Name', models.CharField(max_length=128, null=True, verbose_name='会务组成员姓名')),
                ('conferenceTeam_Sex', models.CharField(choices=[('0', '男'), ('1', '女')], max_length=6, null=True, verbose_name='性别')),
                ('conferenceTeam_Birth', models.DateTimeField(null=True, verbose_name='出生日期')),
                ('conferenceTeam_Type', models.CharField(choices=[('0', '教师'), ('1', '学生')], max_length=6, null=True, verbose_name='类别')),
                ('conferenceTeam_Phone', models.CharField(max_length=11, null=True, verbose_name='手机号')),
                ('conferenceTeam_Work', models.TextField(null=True, verbose_name='主要分工')),
            ],
            options={
                'verbose_name': '会务组',
                'verbose_name_plural': '会务组',
            },
        ),
        migrations.CreateModel(
            name='meetingplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_Name', models.CharField(max_length=128, null=True, verbose_name='会场名称')),
                ('meeting_Place', models.CharField(max_length=128, null=True, verbose_name='会场位置')),
                ('meeting_MaxPeople', models.IntegerField(null=True, verbose_name='会场容纳最大人数')),
                ('meeting_Type', models.CharField(choices=[('0', '主会场'), ('1', '分会场')], max_length=1, null=True, verbose_name='会场类型')),
                ('meeting_Leader', models.CharField(max_length=128, null=True, verbose_name='会场负责人')),
                ('conferenceTeam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.conferenceTeam')),
            ],
            options={
                'verbose_name': '会场',
                'verbose_name_plural': '会场',
            },
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_Theme', models.CharField(max_length=128, null=True, verbose_name='报告主题')),
                ('report_StartTime', models.DateTimeField(null=True, verbose_name='报告开始时间')),
                ('report_EndTime', models.DateTimeField(null=True, verbose_name='报告结束时间')),
                ('report_PresenterName', models.CharField(max_length=128, null=True, verbose_name='主持人姓名')),
                ('report_PresenterPhone', models.CharField(max_length=11, null=True, verbose_name='主持人手机号')),
            ],
            options={
                'verbose_name': '报告分组',
                'verbose_name_plural': '报告分组',
            },
        ),
        migrations.RemoveField(
            model_name='bill',
            name='company',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='billnumber',
            field=models.CharField(max_length=50, null=True, verbose_name='发票编号'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pay_Usretype',
            field=models.CharField(choices=[('0', '学生'), ('1', '普通用户'), ('2', 'CCF会员')], max_length=1, null=True, verbose_name='缴费用户类型'),
        ),
        migrations.AddField(
            model_name='user',
            name='vip_number',
            field=models.CharField(max_length=128, null=True, verbose_name='会员号'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentName',
            field=models.CharField(max_length=30, null=True, verbose_name='评论人'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentReviewer',
            field=models.CharField(max_length=30, null=True, verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='comment',
            field=models.CharField(max_length=1000, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='creditfile',
            field=models.FileField(null=True, upload_to='', verbose_name='凭证文件'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_type',
            field=models.CharField(choices=[('0', '在线支付'), ('1', '银行转账'), ('2', '现场刷卡')], max_length=1, null=True, verbose_name='支付类型'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payaccount',
            field=models.CharField(max_length=30, null=True, verbose_name='缴费账号'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paycompany',
            field=models.CharField(max_length=255, null=True, verbose_name='缴费单位名称'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymoney',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='缴费金额'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paytime',
            field=models.DateTimeField(null=True, verbose_name='缴费时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_type',
            field=models.CharField(choices=[('0', '学生'), ('1', '普通用户'), ('2', 'CCF会员')], max_length=1, null=True, verbose_name='注册类型'),
        ),
        migrations.DeleteModel(
            name='bill',
        ),
    ]
